# Generated by Django 5.2.4 on 2025-08-27 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pagasys", "0022_holidayauditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("api_key", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("radius_m", models.PositiveIntegerField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="pagasys.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="pagasys.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="pagasys.department",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devices",
                        to="pagasys.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrollmentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("max_uses", models.PositiveSmallIntegerField(default=1)),
                ("uses", models.PositiveSmallIntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaceEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_id", models.CharField(max_length=128)),
                ("face_ids", models.JSONField(default=list)),
                ("status", models.CharField(default="active", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_enrollment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PunchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("in", "in"), ("out", "out"), ("auto", "auto")],
                        default="auto",
                        max_length=8,
                    ),
                ),
                ("device_ts", models.DateTimeField()),
                ("server_ts", models.DateTimeField(auto_now_add=True)),
                ("s3_key", models.CharField(blank=True, max_length=300)),
                ("image_bytes_sha256", models.CharField(blank=True, max_length=64)),
                ("face_matched", models.BooleanField(default=False)),
                (
                    "face_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("roster_date", models.DateField(blank=True, null=True)),
                ("requires_face", models.BooleanField(default=False)),
                ("out_of_scope", models.BooleanField(default=False)),
                ("geofence_ok", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("external_id", models.CharField(blank=True, max_length=64)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagasys.company",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="capture.attendancedevice",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matched_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PunchException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("face_required_no_match", "face required but no match"),
                            ("no_enrollment", "employee has no active face enrollment"),
                            ("outside_scope", "outside scope"),
                            ("geofence", "geofence violation"),
                        ],
                        max_length=40,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exception",
                        to="capture.punchevent",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="attendancedevice",
            index=models.Index(
                fields=["company", "branch", "department", "project"],
                name="capture_att_company_e16f0f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancedevice",
            index=models.Index(
                fields=["api_key"], name="capture_att_api_key_f33a95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentlink",
            index=models.Index(
                fields=["token", "expires_at"], name="capture_enr_token_bb6ff1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="punchevent",
            index=models.Index(
                fields=["company", "employee", "device_ts"],
                name="capture_pun_company_fe60fa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="punchevent",
            index=models.Index(
                fields=["device", "external_id"], name="capture_pun_device__bb9c8b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="punchevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("device", "external_id"),
                name="uniq_device_external_id_nonempty",
            ),
        ),
    ]
