# Generated by Django 5.2.4 on 2025-08-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="punchevent",
            name="geofence_ok",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
