# Generated by Django 5.2.4 on 2025-08-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0002_alter_punchevent_geofence_ok"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faceenrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("revoked", "revoked"),
                    ("pending", "pending"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="geofence_ok",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="punchexception",
            name="kind",
            field=models.CharField(
                choices=[
                    ("face_required_no_match", "face required but no match"),
                    ("no_enrollment", "employee has no active face enrollment"),
                    ("face_mismatch", "face mismatch"),
                    ("outside_scope", "outside scope"),
                    ("geofence", "geofence violation"),
                ],
                max_length=40,
            ),
        ),
    ]
