# Generated by Django 5.2.4 on 2025-08-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0003_alter_faceenrollment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="punchevent",
            name="geofence_rule_violation",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="geofence_ok",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="punchexception",
            name="kind",
            field=models.CharField(
                choices=[
                    ("face_required_no_match", "face required but no match"),
                    ("no_enrollment", "employee has no active face enrollment"),
                    ("face_mismatch", "face mismatch"),
                    ("outside_scope", "outside scope"),
                    ("geofence", "geofence violation"),
                    ("geofence_rule", "geofence rule violation"),
                ],
                max_length=40,
            ),
        ),
    ]
