# Generated by Django 5.2.4 on 2025-08-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0004_punchevent_geofence_rule_violation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="punchevent",
            name="roster_fallback",
            field=models.BooleanField(default=False),
        ),
    ]
