# Generated by Django 5.2.4 on 2025-08-29 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0005_punchevent_roster_fallback"),
        ("pagasys", "0022_holidayauditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancedevice",
            name="api_key",
            field=models.CharField(
                help_text="Generated key supplied via the X-Device-Key header",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancedevice",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Limit device usage to this branch",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="pagasys.branch",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedevice",
            name="company",
            field=models.ForeignKey(
                help_text="Owning company for the device",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="pagasys.company",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedevice",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Limit device usage to this department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="pagasys.department",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedevice",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Inactive devices may not submit punches"
            ),
        ),
        migrations.AlterField(
            model_name="attendancedevice",
            name="last_seen",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time the device contacted the API",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancedevice",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Geofence latitude in decimal degrees",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancedevice",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Geofence longitude in decimal degrees",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendancedevice",
            name="name",
            field=models.CharField(
                help_text="Human friendly device label", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="attendancedevice",
            name="note",
            field=models.CharField(
                blank=True, help_text="Internal note", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="attendancedevice",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Limit device usage to this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="pagasys.project",
            ),
        ),
        migrations.AlterField(
            model_name="attendancedevice",
            name="radius_m",
            field=models.PositiveIntegerField(
                blank=True, help_text="Geofence radius in metres", null=True
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentlink",
            name="employee",
            field=models.ForeignKey(
                help_text="Employee who will use this link",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollment_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentlink",
            name="expires_at",
            field=models.DateTimeField(help_text="Timestamp when the link expires"),
        ),
        migrations.AlterField(
            model_name="enrollmentlink",
            name="max_uses",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Maximum times the link may be used"
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentlink",
            name="token",
            field=models.CharField(
                help_text="Unique token embedded in the enrollment URL",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentlink",
            name="used_at",
            field=models.DateTimeField(
                blank=True, help_text="When the link was used", null=True
            ),
        ),
        migrations.AlterField(
            model_name="enrollmentlink",
            name="uses",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Number of times the link has been used"
            ),
        ),
        migrations.AlterField(
            model_name="faceenrollment",
            name="collection_id",
            field=models.CharField(
                help_text="Rekognition collection identifier", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="faceenrollment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Creation timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="faceenrollment",
            name="employee",
            field=models.OneToOneField(
                help_text="Employee that owns the indexed faces",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="face_enrollment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="faceenrollment",
            name="face_ids",
            field=models.JSONField(
                default=list, help_text="List of Rekognition face IDs for the employee"
            ),
        ),
        migrations.AlterField(
            model_name="faceenrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("revoked", "revoked"),
                    ("pending", "pending"),
                ],
                default="active",
                help_text="Current enrollment status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="faceenrollment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="action",
            field=models.CharField(
                choices=[("in", "in"), ("out", "out"), ("auto", "auto")],
                default="auto",
                help_text="Punch direction supplied by the device",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="company",
            field=models.ForeignKey(
                help_text="Owning company",
                on_delete=django.db.models.deletion.PROTECT,
                to="pagasys.company",
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="device",
            field=models.ForeignKey(
                help_text="Device that recorded the punch",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="capture.attendancedevice",
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="device_ts",
            field=models.DateTimeField(help_text="Timestamp reported by the device"),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee identifier supplied by the device",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="Optional client supplied identifier to deduplicate events",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="face_confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Confidence score from Rekognition",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="face_matched",
            field=models.BooleanField(
                default=False, help_text="True when a face match was found"
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="geofence_ok",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="True if the punch was within the device geofence",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="geofence_rule_violation",
            field=models.BooleanField(
                default=False, help_text="Device or shift violated geofence rule"
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="image_bytes_sha256",
            field=models.CharField(
                blank=True, help_text="SHA256 hash of the uploaded image", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="matched_employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee matched via face recognition",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="notes",
            field=models.CharField(
                blank=True, help_text="Reason punch was not accepted", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="out_of_scope",
            field=models.BooleanField(
                default=False, help_text="Employee outside the device's scope"
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="requires_face",
            field=models.BooleanField(
                default=False, help_text="Shift required face verification"
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="roster_date",
            field=models.DateField(
                blank=True, help_text="Resolved roster date for the punch", null=True
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="roster_fallback",
            field=models.BooleanField(
                default=False, help_text="Roster date was inferred from last punch"
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="s3_key",
            field=models.CharField(
                blank=True, help_text="S3 key where the image is stored", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="punchevent",
            name="server_ts",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp recorded by the server"
            ),
        ),
        migrations.AlterField(
            model_name="punchexception",
            name="details",
            field=models.JSONField(
                default=dict, help_text="Additional structured details for debugging"
            ),
        ),
        migrations.AlterField(
            model_name="punchexception",
            name="event",
            field=models.OneToOneField(
                help_text="Punch event that triggered the exception",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exception",
                to="capture.punchevent",
            ),
        ),
        migrations.AlterField(
            model_name="punchexception",
            name="kind",
            field=models.CharField(
                choices=[
                    ("face_required_no_match", "face required but no match"),
                    ("no_enrollment", "employee has no active face enrollment"),
                    ("face_mismatch", "face mismatch"),
                    ("outside_scope", "outside scope"),
                    ("geofence", "geofence violation"),
                    ("geofence_rule", "geofence rule violation"),
                ],
                help_text="Type of exception encountered",
                max_length=40,
            ),
        ),
    ]
