# Generated by Django 5.2.4 on 2025-09-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0006_alter_attendancedevice_api_key_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="punchevent",
            index=models.Index(fields=["roster_date"], name="capture_pun_roster_idx"),
        ),
    ]
