# Generated by Django 5.2.4 on 2025-09-15 11:35

from django.db import migrations, models


def rename_legacy_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        'ALTER INDEX IF EXISTS "capture_punchevent_roster_idx" '
        'RENAME TO "capture_pun_roster_idx";'
    )


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0008_punchevent_processed"),
    ]

    operations = [
        migrations.RunPython(
            rename_legacy_index, reverse_code=migrations.RunPython.noop
        ),
        migrations.RenameIndex(
            model_name="punchevent",
            old_name="capture_pun_roster_idx",
            new_name="capture_pun_roster__1b86e9_idx",
        ),
        migrations.AlterField(
            model_name="enrollmentlink",
            name="token",
            field=models.CharField(
                editable=False,
                help_text="Unique token embedded in the enrollment URL",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="punchexception",
            name="kind",
            field=models.CharField(
                choices=[
                    ("face_required_no_match", "face required but no match"),
                    ("no_enrollment", "employee has no active face enrollment"),
                    ("duplicate", "duplicate punch"),
                ],
                help_text="Type of exception encountered",
                max_length=40,
            ),
        ),
    ]

