# Generated by Django 5.2.4 on 2025-09-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capture", "0008_punchevent_processed"),
    ]

    operations = [
        # Make the index rename resilient: do it only if the old name exists,
        # but still update Django's state so future migrations match.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "capture_pun_roster_idx" RENAME TO "capture_pun_roster__1b86e9_idx";',
                    'ALTER INDEX IF EXISTS "capture_pun_roster__1b86e9_idx" RENAME TO "capture_pun_roster_idx";',
                ),
                # Optional extra safety if an older name variant was used previously:
                migrations.RunSQL(
                    'ALTER INDEX IF EXISTS "capture_punchevent_roster_idx" RENAME TO "capture_pun_roster__1b86e9_idx";',
                    'ALTER INDEX IF EXISTS "capture_pun_roster__1b86e9_idx" RENAME TO "capture_punchevent_roster_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="punchevent",
                    old_name="capture_pun_roster_idx",
                    new_name="capture_pun_roster__1b86e9_idx",
                ),
            ],
        ),

        migrations.AlterField(
            model_name="enrollmentlink",
            name="token",
            field=models.CharField(
                editable=False,
                help_text="Unique token embedded in the enrollment URL",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="punchexception",
            name="kind",
            field=models.CharField(
                choices=[
                    ("face_required_no_match", "face required but no match"),
                    ("no_enrollment", "employee has no active face enrollment"),
                    ("duplicate", "duplicate punch"),
                ],
                help_text="Type of exception encountered",
                max_length=40,
            ),
        ),
    ]

