# Generated by Django 5.2.4 on 2025-09-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0009_rename_capture_pun_roster_idx_capture_pun_roster__1b86e9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchexception',
            name='kind',
            field=models.CharField(choices=[('face_required_no_match', 'face required but no match'), ('no_enrollment', 'employee has no active face enrollment'), ('face_mismatch', 'face mismatch'), ('outside_scope', 'outside scope'), ('geofence', 'geofence violation'), ('geofence_rule', 'geofence rule violation'), ('duplicate', 'duplicate punch')], help_text='Type of exception encountered', max_length=40),
        ),
    ]
