"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from celery.schedules import crontab
import os
import environ
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from corsheaders.defaults import default_headers

# Load environment variables
env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(env.str('ENV_FILE', '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Provide fallbacks for unit tests if environment variables are not set.
SECRET_KEY = env("SECRET_KEY", default="test-secret")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=True)

# Allow localhost by default and permit Elastic Beanstalk domains in production
ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS", default=["localhost", ".elasticbeanstalk.com", "127.0.0.1", "0.0.0.0", "api.pagasys.pro", "pagasysv1.vercel.app", "prodapi.pagasys.pro", "ats.pagasys.pro"]
)

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=[
        "https://ats.pagasys.pro",
        "https://api.pagasys.pro",
        "https://pagasys.pro",
        "https://prodapi.pagasys.pro",
        "http://localhost:3000"
    ],
)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + ["x-device-key"]

# Allow cross-site requests from trusted domains for CSRF protection
CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "http://localhost:3000",
        "https://pagasyss.me-central-1.elasticbeanstalk.com",
        "https://api.pagasys.pro",
        "https://ats.pagasys.pro",
        "https://prodapi.pagasys.pro",
    ],
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "grappelli",
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "django_filters",
    "drf_spectacular",
    "pagasys",
    "capture",
    "attendance",
    "django_ratelimit",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "pagasys.middleware.CompanyTimezoneMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def _pg_from_env():
    """Build a PostgreSQL config from environment variables.

    This helper prefers explicit ``DB_*`` variables but will fall back to the
    older ``RDS_*`` names.  If **any** of the core settings are provided we
    require that **all** of them are present; otherwise Django would silently
    fall back to the SQLite configuration.  Raising an ``ImproperlyConfigured``
    error makes misconfiguration immediately visible.
    """

    # Prefer DB_* if present, otherwise fall back to RDS_*
    host = env("DB_HOST", default=env("RDS_HOSTNAME", default=None))
    name = env("DB_NAME", default=env("RDS_DB_NAME", default=None))
    user = env("DB_USER", default=env("RDS_USERNAME", default=None))
    password = env("DB_PASSWORD", default=env("RDS_PASSWORD", default=None))
    port = env("DB_PORT", default=env("RDS_PORT", default="5432"))

    # If any of the core settings are provided but not all, raise an error
    core_settings = {
        "DB_HOST": host,
        "DB_NAME": name,
        "DB_USER": user,
        "DB_PASSWORD": password,
    }
    provided_values = list(core_settings.values())
    if any(provided_values) and not all(provided_values):
        missing = [k for k, v in core_settings.items() if not v]
        raise ImproperlyConfigured(
            "Incomplete database configuration; missing: " + ", ".join(missing)
        )

    if all(provided_values):
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": name,
            "USER": user,
            "PASSWORD": password,
            "HOST": host,
            "PORT": port,
            "CONN_MAX_AGE": env.int("DB_CONN_MAX_AGE", default=600),
            # Use 'require' by default; override with DB_SSLMODE if needed
            "OPTIONS": {"sslmode": env("DB_SSLMODE", default="require")},
        }
    return None

DATABASE_URL = env("DATABASE_URL", default=None)

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=env.int("DB_CONN_MAX_AGE", default=600),
            ssl_require=env.bool("DB_SSL_REQUIRE", default=True),
        )
    }
else:
    pg_cfg = _pg_from_env()
    if pg_cfg:
        DATABASES = {"default": pg_cfg}
    else:
        # Final fallback for local/dev: SQLite
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "pagasys.Employee"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.DjangoModelPermissions',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'pagasys.pagination.GlobalPagination',
    'PAGE_SIZE': 100,
    'MAX_PAGE_SIZE': 1000,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER': 'pagasys.policy.exceptions.unified_exception_handler',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Pagasys Payroll API',
    'DESCRIPTION': 'Complete HR, payroll, and capture management for UAE companies',
    'VERSION': '1.0.0',
}

# --- CAPTURE LAYER CONFIG ---
AWS_REKOGNITION_REGION = env("AWS_REKOGNITION_REGION", default="ap-south-1")
AWS_REKOGNITION_COLLECTION_PREFIX = env(
    "AWS_REKOGNITION_COLLECTION_PREFIX", default="reko-company"
)
AWS_S3_BUCKET_ENROLL = env("AWS_S3_BUCKET_ENROLL", default="carhub-pagasys-enroll-ap-south-1")
AWS_S3_BUCKET_CAPTURE = env("AWS_S3_BUCKET_CAPTURE", default="carhub-pagasys-capture-ap-south-1")
PUBLIC_BASE_URL = env("PUBLIC_BASE_URL", default="https://api.pagasys.pro")

FACE_MATCH_DEFAULT_MIN_CONF = env.float("FACE_MATCH_DEFAULT_MIN_CONF", default=0.90)
CAPTURE_BLOCK_OUT_OF_SCOPE = env.bool("CAPTURE_BLOCK_OUT_OF_SCOPE", default=False)
CAPTURE_BLOCK_GEOFENCE = env.bool("CAPTURE_BLOCK_GEOFENCE", default=False)
# Maximum punch submissions per IP (e.g. "30/m" => 30 per minute)
CAPTURE_PUNCH_RATE_LIMIT = env("CAPTURE_PUNCH_RATE_LIMIT", default="30/m")

FACE_ENROLL_MIN_PHOTOS = env.int("FACE_ENROLL_MIN_PHOTOS", default=3)
FACE_ENROLL_MAX_PHOTOS = env.int("FACE_ENROLL_MAX_PHOTOS", default=6)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(seconds=int(env('SIMPLE_JWT_ACCESS_TOKEN_LIFETIME', default='3600'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(seconds=int(env('SIMPLE_JWT_REFRESH_TOKEN_LIFETIME', default='86400'))),
    'SIGNING_KEY': env('SIMPLE_JWT_SIGNING_KEY', default=SECRET_KEY),
    'ALGORITHM': env('SIMPLE_JWT_ALGORITHM', default='HS256'),
}

# Celery configuration
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://redis:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default=CELERY_BROKER_URL)
CELERY_TASK_ALWAYS_EAGER = env.bool('CELERY_TASK_ALWAYS_EAGER', default=False)
CELERY_TASK_EAGER_PROPAGATES = env.bool('CELERY_TASK_EAGER_PROPAGATES', default=True)

CELERY_BEAT_SCHEDULE = {
    "attendance-nightly-recompute": {
        "task": "attendance.tasks.recompute_yesterday_task",
        "schedule": crontab(hour=2, minute=0),
    }
}

SILENCED_SYSTEM_CHECKS = [
    "security.W019",
    "django_ratelimit.E003",
    "django_ratelimit.W001",
]
