# Generated by Django 5.2.4 on 2025-07-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name_plural": "branches"},
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "companies"},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name_plural": "departments"},
        ),
        migrations.AlterModelOptions(
            name="designation",
            options={"verbose_name_plural": "designations"},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name_plural": "employees"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name_plural": "projects"},
        ),
        migrations.AlterModelOptions(
            name="tradelicense",
            options={
                "verbose_name": "trade license",
                "verbose_name_plural": "trade licenses",
            },
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(help_text="Branch office name", max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(help_text="Official company name", max_length=255),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(help_text="Department name", max_length=255),
        ),
        migrations.AlterField(
            model_name="designation",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of this designation"
            ),
        ),
        migrations.AlterField(
            model_name="designation",
            name="level",
            field=models.PositiveIntegerField(
                blank=True, help_text="Seniority level", null=True
            ),
        ),
        migrations.AlterField(
            model_name="designation",
            name="name",
            field=models.CharField(help_text="Job title name", max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department assigned",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="pagasys.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                help_text="Job designation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="pagasys.designation",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project assigned",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="pagasys.project",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="trade_license",
            field=models.ForeignKey(
                help_text="Visa license assigned",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="pagasys.tradelicense",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, help_text="Project end date", null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(help_text="Project name", max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(help_text="Project start date"),
        ),
        migrations.AlterField(
            model_name="tradelicense",
            name="expiry_date",
            field=models.DateField(help_text="Date license expires"),
        ),
        migrations.AlterField(
            model_name="tradelicense",
            name="issued_date",
            field=models.DateField(help_text="Date license was issued"),
        ),
        migrations.AlterField(
            model_name="tradelicense",
            name="license_no",
            field=models.CharField(
                help_text="Official license number", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tradelicense",
            name="max_visas",
            field=models.PositiveIntegerField(help_text="Maximum number of visa slots"),
        ),
    ]
