# Generated by Django 5.2.4 on 2025-07-23 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0003_license_company_branches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="company",
            field=models.ForeignKey(
                help_text="Parent company",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="pagasys.company",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="branch",
            field=models.ForeignKey(
                help_text="Branch that houses the department",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="pagasys.branch",
            ),
        ),
        migrations.AlterField(
            model_name="designation",
            name="company",
            field=models.ForeignKey(
                help_text="Company that defines the designation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="designations",
                to="pagasys.company",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                choices=[("permanent", "Permanent"), ("temporary", "Temporary")],
                help_text="Employment contract type",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(help_text="Given name", max_length=255),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(help_text="Date hired"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(help_text="Family name", max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="branch",
            field=models.ForeignKey(
                help_text="Branch executing the project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="pagasys.branch",
            ),
        ),
        migrations.AlterField(
            model_name="tradelicense",
            name="company",
            field=models.ForeignKey(
                help_text="License owning company",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="pagasys.company",
            ),
        ),
    ]
