# Generated by Django 5.2.4 on 2025-07-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0005_alter_employee_managers_employee_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["id"], "verbose_name_plural": "companies"},
        ),
    ]
