# Generated by Django 5.2.4 on 2025-07-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagasys', '0006_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id'], 'verbose_name_plural': 'employees'},
        ),
    ]
