# Generated by Django 5.2.4 on 2025-07-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagasys', '0007_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id'], 'verbose_name_plural': 'departments'},
        ),
    ]
