# Generated by Django 5.2.4 on 2025-07-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pagasys", "0008_alter_department_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="branch",
            index=models.Index(
                fields=["company", "name"], name="branch_company_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["name"], name="company_name_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["branch", "name"], name="dept_branch_name_idx"),
        ),
        migrations.AddIndex(
            model_name="designation",
            index=models.Index(
                fields=["company", "name", "level"],
                name="designation_comp_name_lvl_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["trade_license", "department", "employment_type"],
                name="emp_lic_dept_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["trade_license", "project", "employment_type"],
                name="emp_lic_proj_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["department", "designation", "employment_type"],
                name="emp_dept_desig_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["project", "designation", "employment_type"],
                name="emp_proj_desig_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["first_name", "last_name"], name="emp_name_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["branch", "name"], name="project_branch_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["branch", "start_date", "end_date"],
                name="project_date_range_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tradelicense",
            index=models.Index(
                fields=["company", "license_no"], name="license_company_no_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradelicense",
            index=models.Index(
                fields=["company", "issued_date", "expiry_date"],
                name="license_date_range_idx",
            ),
        ),
    ]
