# Generated by Django 5.2.4 on 2025-07-27 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pagasys", "0009_add_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"ordering": ["id"], "verbose_name_plural": "branches"},
        ),
        migrations.AlterModelOptions(
            name="designation",
            options={"ordering": ["id"], "verbose_name_plural": "designations"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["id"], "verbose_name_plural": "projects"},
        ),
        migrations.AlterModelOptions(
            name="tradelicense",
            options={
                "ordering": ["id"],
                "verbose_name": "trade license",
                "verbose_name_plural": "trade licenses",
            },
        ),
        migrations.RemoveConstraint(
            model_name="employee",
            name="employee_must_have_license",
        ),
        migrations.AddField(
            model_name="employee",
            name="visa_type",
            field=models.CharField(
                choices=[("company", "Company"), ("personal", "Personal")],
                default="company",
                help_text="Whether the employee uses a company or personal visa",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="trade_license",
            field=models.ForeignKey(
                blank=True,
                help_text="Visa license assigned",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="pagasys.tradelicense",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("trade_license__isnull", False), ("visa_type", "company")
                    ),
                    models.Q(
                        ("trade_license__isnull", True), ("visa_type", "personal")
                    ),
                    _connector="OR",
                ),
                name="employee_license_matches_visa_type",
            ),
        ),
    ]
