# Generated by Django 5.2.4 on 2025-08-15 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0010_add_visa_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("IN", "In"), ("OUT", "Out"), ("UNK", "Unknown")],
                        help_text="Punch direction",
                        max_length=3,
                    ),
                ),
                ("ts", models.DateTimeField(help_text="Timestamp in UTC")),
                (
                    "provider",
                    models.CharField(
                        help_text="Event provider identifier", max_length=50
                    ),
                ),
                (
                    "face_confidence",
                    models.FloatField(
                        blank=True, help_text="Face match confidence", null=True
                    ),
                ),
                (
                    "liveness",
                    models.FloatField(
                        blank=True, help_text="Liveness score from provider", null=True
                    ),
                ),
                (
                    "signed_payload",
                    models.TextField(help_text="Original signed payload"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company of the employee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_events",
                        to="pagasys.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee generating the event",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "attendance event",
                "verbose_name_plural": "attendance events",
                "ordering": ["ts"],
            },
        ),
        migrations.CreateModel(
            name="AttPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("suspect", "Suspect"),
                            ("missing", "Missing"),
                        ],
                        default="good",
                        help_text="Pair quality",
                        max_length=20,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee for the pair",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_pairs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "in_event",
                    models.ForeignKey(
                        help_text="In event",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pair_as_in",
                        to="pagasys.attevent",
                    ),
                ),
                (
                    "out_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Out event",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pair_as_out",
                        to="pagasys.attevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "attendance pair",
                "verbose_name_plural": "attendance pairs",
                "ordering": ["in_event__ts"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Device identifier", max_length=100),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("kiosk", "Kiosk"),
                            ("mobile", "Mobile"),
                            ("web", "Web"),
                        ],
                        help_text="Device type",
                        max_length=10,
                    ),
                ),
                (
                    "hmac_secret",
                    models.CharField(
                        help_text="Shared secret for validating payload signatures",
                        max_length=64,
                    ),
                ),
                (
                    "geofence",
                    models.JSONField(
                        blank=True,
                        help_text="Optional geofence definition for device location",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company that owns the device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="pagasys.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "device",
                "verbose_name_plural": "devices",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="attevent",
            name="device",
            field=models.ForeignKey(
                help_text="Device used for the event",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="pagasys.device",
            ),
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(help_text="Start date")),
                ("end_date", models.DateField(help_text="End date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Request status",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, help_text="Optional reason")),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Requesting employee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "leave request",
                "verbose_name_plural": "leave requests",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Leave date")),
                (
                    "minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Leave minutes on this date"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        help_text="Parent leave request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="pagasys.leaverequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "leave day",
                "verbose_name_plural": "leave days",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Leave type name", max_length=100)),
                (
                    "pay_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of pay during leave",
                        max_digits=5,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company defining the leave type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_types",
                        to="pagasys.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "leave type",
                "verbose_name_plural": "leave types",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="leave_type",
            field=models.ForeignKey(
                help_text="Leave type",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="pagasys.leavetype",
            ),
        ),
        migrations.CreateModel(
            name="ShiftRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ramadan_reduce_minutes",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Daily minute reduction during Ramadan"
                    ),
                ),
                (
                    "weekly_rest_day",
                    models.PositiveSmallIntegerField(
                        default=6, help_text="Weekly rest day (0=Mon ... 6=Sun)"
                    ),
                ),
                (
                    "night_ot_start",
                    models.TimeField(
                        blank=True, help_text="Night OT window start", null=True
                    ),
                ),
                (
                    "night_ot_end",
                    models.TimeField(
                        blank=True, help_text="Night OT window end", null=True
                    ),
                ),
                (
                    "max_daily_hours",
                    models.PositiveSmallIntegerField(
                        default=24, help_text="Maximum allowed daily work hours"
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        help_text="Company these rules apply to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_rule",
                        to="pagasys.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "shift rule",
                "verbose_name_plural": "shift rules",
                "ordering": ["company"],
            },
        ),
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Shift name", max_length=100)),
                ("start_time", models.TimeField(help_text="Start time")),
                ("end_time", models.TimeField(help_text="End time")),
                (
                    "break_minutes",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Total break minutes"
                    ),
                ),
                (
                    "grace_minutes",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Grace minutes before late"
                    ),
                ),
                (
                    "rounding",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Rounding minutes for calculations"
                    ),
                ),
                (
                    "cross_midnight",
                    models.BooleanField(
                        default=False, help_text="Shift crosses midnight"
                    ),
                ),
                (
                    "requires_face",
                    models.BooleanField(
                        default=False, help_text="Face recognition required"
                    ),
                ),
                (
                    "shift_worker_night_exempt",
                    models.BooleanField(
                        default=False, help_text="Shift workers exempt from night OT"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company defining the shift",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_templates",
                        to="pagasys.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "shift template",
                "verbose_name_plural": "shift templates",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Roster date")),
                (
                    "overrides",
                    models.JSONField(
                        blank=True,
                        help_text="Optional calculation overrides",
                        null=True,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee assigned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        help_text="Shift to apply",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_entries",
                        to="pagasys.shifttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "roster entry",
                "verbose_name_plural": "roster entries",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="WorkCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Calendar name", max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company using the calendar",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendars",
                        to="pagasys.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "work calendar",
                "verbose_name_plural": "work calendars",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Holiday date")),
                ("name", models.CharField(help_text="Holiday name", max_length=100)),
                (
                    "calendar",
                    models.ForeignKey(
                        help_text="Calendar containing this holiday",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="pagasys.workcalendar",
                    ),
                ),
            ],
            options={
                "verbose_name": "holiday",
                "verbose_name_plural": "holidays",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="AttDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Calendar date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("leave", "Leave"),
                            ("holiday", "Holiday"),
                        ],
                        help_text="Attendance status",
                        max_length=20,
                    ),
                ),
                (
                    "work_minutes",
                    models.PositiveIntegerField(default=0, help_text="Worked minutes"),
                ),
                (
                    "late_minutes",
                    models.PositiveIntegerField(default=0, help_text="Late minutes"),
                ),
                (
                    "early_leave_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Minutes left early"
                    ),
                ),
                (
                    "ot125_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Overtime minutes at 1.25x"
                    ),
                ),
                (
                    "ot150_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Overtime minutes at 1.50x"
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional notes"
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False, help_text="Locked from recalculation"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee for the day",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "attendance day",
                "verbose_name_plural": "attendance days",
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date"], name="attday_employee_date_idx"
                    )
                ],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="attevent",
            index=models.Index(
                fields=["company", "employee", "ts"], name="att_event_comp_emp_ts_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("direction", "UNK"), _negated=True),
                fields=("employee", "ts", "device"),
                name="att_event_emp_ts_device_unique",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaveday",
            unique_together={("request", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="leavetype",
            unique_together={("company", "name")},
        ),
        migrations.AddIndex(
            model_name="rosterentry",
            index=models.Index(
                fields=["employee", "date"], name="roster_employee_date_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rosterentry",
            unique_together={("employee", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="workcalendar",
            unique_together={("company", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("calendar", "date")},
        ),
    ]
