# Generated by Django 5.2.4 on 2025-08-20 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0010_add_visa_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=100)),
                ("start_time", models.TimeField(help_text="Scheduled start time")),
                ("end_time", models.TimeField(help_text="Scheduled end time")),
                (
                    "cross_midnight",
                    models.BooleanField(
                        default=False, help_text="Does shift end next day?"
                    ),
                ),
                (
                    "break_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Total unpaid break minutes"
                    ),
                ),
                (
                    "grace_in_min",
                    models.PositiveIntegerField(
                        default=0, help_text="Minutes allowed late without penalty"
                    ),
                ),
                (
                    "grace_out_min",
                    models.PositiveIntegerField(
                        default=0, help_text="Minutes allowed early without penalty"
                    ),
                ),
                (
                    "late_after_min",
                    models.PositiveIntegerField(
                        default=0, help_text="Mark late after this many minutes"
                    ),
                ),
                (
                    "early_leave_before_min",
                    models.PositiveIntegerField(
                        default=0, help_text="Mark early leave before this many minutes"
                    ),
                ),
                (
                    "rounding_min",
                    models.PositiveIntegerField(
                        default=0, help_text="Rounding increment in minutes"
                    ),
                ),
                (
                    "requires_face",
                    models.BooleanField(
                        default=False, help_text="Require face authentication"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company owning this template",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_templates",
                        to="pagasys.company",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ShiftRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fixed_break_window", "fixed break window"),
                            (
                                "required_break_after_consecutive",
                                "required break after consecutive",
                            ),
                            ("min_total_break_per_day", "min total break per day"),
                            ("paid_break_window", "paid break window"),
                            ("night_ot_window", "night ot window"),
                            ("ramadan_reduce_minutes", "Ramadan reduce minutes"),
                            ("weekly_rest_day", "weekly rest day"),
                            ("max_daily_hours", "max daily hours"),
                            ("geofence_required", "geofence required"),
                            ("face_min_conf", "face minimum confidence"),
                        ],
                        max_length=40,
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "params",
                    models.JSONField(
                        blank=True, help_text="Additional parameters", null=True
                    ),
                ),
                ("active_from", models.DateField(blank=True, null=True)),
                ("active_to", models.DateField(blank=True, null=True)),
                (
                    "weekdays",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated weekdays e.g. MON,TUE",
                        max_length=20,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        help_text="Shift template this rule applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="pagasys.shifttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Shift start date")),
                ("override_start", models.TimeField(blank=True, null=True)),
                ("override_end", models.TimeField(blank=True, null=True)),
                ("is_rest_day", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee for the roster entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        help_text="Shift template applied",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_entries",
                        to="pagasys.shifttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="WorkCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Calendar name", max_length=255)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Use as default when none assigned"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company this calendar belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendars",
                        to="pagasys.company",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Holiday date")),
                ("name", models.CharField(help_text="Holiday name", max_length=255)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Public vs company holiday"
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        help_text="Parent work calendar",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="pagasys.workcalendar",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="Short code e.g. AL", max_length=20),
                ),
                (
                    "name",
                    models.CharField(help_text="Descriptive name", max_length=100),
                ),
                (
                    "paid_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Percent of pay the leave grants",
                        max_digits=5,
                    ),
                ),
                (
                    "requires_doc",
                    models.BooleanField(
                        default=False, help_text="Whether documentation is required"
                    ),
                ),
                (
                    "max_days_per_year",
                    models.PositiveIntegerField(
                        blank=True, help_text="Maximum days allowed per year", null=True
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True, help_text="Extra configuration", null=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company defining this leave type",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_types",
                        to="pagasys.company",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["company", "code"], name="leavetype_company_code_idx"
                    )
                ],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.AddIndex(
            model_name="shifttemplate",
            index=models.Index(
                fields=["company", "name"], name="shifttemplate_company_name_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shifttemplate",
            unique_together={("company", "name")},
        ),
        migrations.AddIndex(
            model_name="shiftrule",
            index=models.Index(
                fields=["shift", "kind"], name="shiftrule_shift_kind_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rosterentry",
            index=models.Index(
                fields=["employee", "date"], name="roster_employee_date_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rosterentry",
            unique_together={("employee", "date")},
        ),
        migrations.AddIndex(
            model_name="workcalendar",
            index=models.Index(
                fields=["company", "name"], name="calendar_company_name_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workcalendar",
            unique_together={("company", "name")},
        ),
        migrations.AddIndex(
            model_name="holiday",
            index=models.Index(
                fields=["calendar", "date"], name="holiday_calendar_date_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("calendar", "date")},
        ),
    ]
