# Generated by Django 5.2.4 on 2025-08-15 13:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pagasys",
            "0011_attevent_attpair_device_attevent_device_leaverequest_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attday",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Shift template used for this day’s calculation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pagasys.shifttemplate",
            ),
        ),
        migrations.AddField(
            model_name="attpair",
            name="duration_min",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attpair",
            name="in_ts",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attpair",
            name="out_ts",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attday",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("leave", "Leave"),
                    ("holiday", "Holiday"),
                    ("rest", "Rest Day"),
                    ("missing", "Missing Punch"),
                ],
                help_text="Attendance status",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="attpair",
            index=models.Index(fields=["employee", "in_ts"], name="attpair_emp_in_idx"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["company", "device_type"], name="device_company_type_idx"
            ),
        ),
    ]
