# Generated by Django 5.2.4 on 2025-08-20 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0011_shifttemplate_shiftrule_rosterentry_workcalendar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="work_calendar",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific work calendar for this branch",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="pagasys.workcalendar",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="work_calendar",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific work calendar for the employee",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="pagasys.workcalendar",
            ),
        ),
    ]
