# Generated by Django 5.2.4 on 2025-08-15 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0012_attday_shift_attpair_duration_min_attpair_in_ts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveday",
            name="pay_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Override pay percentage for this day",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="pay_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Override pay percentage for this request",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="workcalendar",
            name="is_default",
            field=models.BooleanField(
                default=False, help_text="Default calendar for the company"
            ),
        ),
        migrations.AlterField(
            model_name="attday",
            name="early_leave_minutes",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Minutes left early"
            ),
        ),
        migrations.AlterField(
            model_name="attday",
            name="late_minutes",
            field=models.PositiveSmallIntegerField(default=0, help_text="Late minutes"),
        ),
        migrations.AlterField(
            model_name="attday",
            name="ot125_minutes",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Overtime minutes at 1.25x"
            ),
        ),
        migrations.AlterField(
            model_name="attday",
            name="ot150_minutes",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Overtime minutes at 1.50x"
            ),
        ),
        migrations.AlterField(
            model_name="attday",
            name="work_minutes",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Worked minutes"
            ),
        ),
        migrations.AlterField(
            model_name="attevent",
            name="face_confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Face match confidence",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attevent",
            name="liveness",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Liveness score from provider",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attpair",
            name="duration_min",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="leaveday",
            name="minutes",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Leave minutes on this date"
            ),
        ),
        migrations.AlterField(
            model_name="leavetype",
            name="pay_percent",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Default percentage of pay during leave",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="shiftrule",
            name="night_ot_end",
            field=models.TimeField(
                blank=True, help_text="Optional night OT window end", null=True
            ),
        ),
        migrations.AlterField(
            model_name="shiftrule",
            name="night_ot_start",
            field=models.TimeField(
                blank=True, help_text="Optional night OT window start", null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="workcalendar",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("company",),
                name="unique_default_calendar_per_company",
            ),
        ),
    ]
