# Generated by Django 5.2.4 on 2025-08-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0012_branch_work_calendar_employee_work_calendar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rosterentry",
            name="is_rest_day",
            field=models.BooleanField(
                default=False, help_text="Marks the day as a scheduled rest day"
            ),
        ),
        migrations.AlterField(
            model_name="rosterentry",
            name="override_end",
            field=models.TimeField(
                blank=True, help_text="Override end time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="rosterentry",
            name="override_start",
            field=models.TimeField(
                blank=True, help_text="Override start time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="shiftrule",
            name="active_from",
            field=models.DateField(
                blank=True, help_text="Rule active start date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="shiftrule",
            name="active_to",
            field=models.DateField(
                blank=True, help_text="Rule active end date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="shiftrule",
            name="kind",
            field=models.CharField(
                choices=[
                    ("fixed_break_window", "fixed break window"),
                    (
                        "required_break_after_consecutive",
                        "required break after consecutive",
                    ),
                    ("min_total_break_per_day", "min total break per day"),
                    ("paid_break_window", "paid break window"),
                    ("night_ot_window", "night ot window"),
                    ("ramadan_reduce_minutes", "Ramadan reduce minutes"),
                    ("weekly_rest_day", "weekly rest day"),
                    ("max_daily_hours", "max daily hours"),
                    ("geofence_required", "geofence required"),
                    ("face_min_conf", "face minimum confidence"),
                ],
                help_text="Rule kind",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="shiftrule",
            name="value",
            field=models.CharField(help_text="Rule value", max_length=100),
        ),
    ]
