# Generated by Django 5.2.4 on 2025-08-16 12:50

from django.db import migrations, models


def alter_liveness_to_boolean(apps, schema_editor):
    """Convert liveness Decimal field to Boolean across databases."""
    AttEvent = apps.get_model("pagasys", "AttEvent")
    old_field = AttEvent._meta.get_field("liveness")
    new_field = models.BooleanField(
        blank=True, help_text="Liveness confirmed by provider", null=True
    )
    new_field.set_attributes_from_name("liveness")
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE pagasys_attevent "
            "ALTER COLUMN liveness TYPE boolean "
            "USING (CASE WHEN liveness IS NULL THEN NULL "
            "WHEN liveness > 0 THEN TRUE ELSE FALSE END)"
        )
    else:
        schema_editor.alter_field(AttEvent, old_field, new_field)


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0013_leaveday_pay_percent_leaverequest_pay_percent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attevent",
            name="face_confidence",
        ),
        migrations.RemoveField(
            model_name="attevent",
            name="signed_payload",
        ),
        migrations.AddField(
            model_name="attevent",
            name="face_conf",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Face match confidence",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attevent",
            name="meta",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional event metadata"
            ),
        ),
        migrations.AddField(
            model_name="attevent",
            name="payload_sig",
            field=models.CharField(
                default="",
                help_text="HMAC signature of canonical payload",
                max_length=64,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(alter_liveness_to_boolean, migrations.RunPython.noop)
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="attevent",
                    name="liveness",
                    field=models.BooleanField(
                        blank=True,
                        help_text="Liveness confirmed by provider",
                        null=True,
                    ),
                )
            ],
        ),
    ]
