# Generated by Django 5.2.4 on 2025-08-20 09:00
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pagasys", "0013_alter_rosterentry_is_rest_day_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workcalendar",
            constraint=models.UniqueConstraint(
                fields=("company",),
                condition=models.Q(is_default=True),
                name="unique_default_calendar_per_company",
            ),
        ),
    ]
