# Generated by Django 5.2.4 on 2025-08-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0013_leaveday_pay_percent_leaverequest_pay_percent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attevent",
            name="face_confidence",
        ),
        migrations.RemoveField(
            model_name="attevent",
            name="signed_payload",
        ),
        migrations.AddField(
            model_name="attevent",
            name="face_conf",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Face match confidence",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attevent",
            name="meta",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional event metadata"
            ),
        ),
        migrations.AddField(
            model_name="attevent",
            name="payload_sig",
            field=models.CharField(
                default="",
                help_text="HMAC signature of canonical payload",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="attevent",
            name="liveness",
            field=models.BooleanField(
                blank=True, help_text="Liveness confirmed by provider", null=True
            ),
        ),
    ]
