# Generated by Django 5.2.4 on 2025-08-16 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0014_remove_attevent_face_confidence_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attevent",
            name="device",
            field=models.ForeignKey(
                help_text="Device used for the event",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="pagasys.device",
            ),
        ),
        migrations.AlterField(
            model_name="attevent",
            name="employee",
            field=models.ForeignKey(
                help_text="Employee generating the event",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
