# Generated by Django 5.2.4 on 2025-08-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0014_workcalendar_default_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shifttemplate",
            name="break_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total unpaid break minutes (must be < shift duration)",
            ),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="early_leave_before_min",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Mark early leave before this many minutes (≥ grace_out_min)",
            ),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="late_after_min",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Mark late after this many minutes (≥ grace_in_min)",
            ),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="rounding_min",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "0"),
                    (1, "1"),
                    (5, "5"),
                    (10, "10"),
                    (15, "15"),
                    (30, "30"),
                ],
                default=0,
                help_text="Rounding increment in minutes (0,1,5,10,15,30)",
            ),
        ),
        migrations.AlterField(
            model_name="workcalendar",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Mark as company default calendar; at most one per company",
            ),
        ),
    ]
