# Generated by Django 5.2.4 on 2025-08-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0015_alter_attevent_device_alter_attevent_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="attpair",
            name="source",
            field=models.CharField(
                choices=[("auto", "Auto"), ("manual", "Manual")],
                default="auto",
                help_text="Who created this pair",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="attpair",
            name="duration_min",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attpair",
            name="quality",
            field=models.CharField(
                choices=[
                    ("ok", "OK"),
                    ("missing_out", "Missing OUT"),
                    ("dup_in", "Duplicate IN"),
                    ("manual", "Manual"),
                ],
                default="ok",
                help_text="Pair quality",
                max_length=20,
            ),
        ),
    ]
