# Generated by Django 5.2.4 on 2025-08-21 13:54

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0015_alter_shifttemplate_break_minutes_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leavetype",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="company",
            name="timezone",
            field=models.CharField(
                default="Asia/Dubai",
                help_text="IANA time zone for scheduling/attendance",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="shiftrule",
            name="params",
            field=models.JSONField(
                blank=True,
                help_text="Additional parameters; break rules require paid (bool) and enforcement (warn, flag, auto_deduct, block)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shiftrule",
            name="value",
            field=models.CharField(
                help_text="Rule value. For time windows use HH:MM-HH:MM and it may cross midnight (e.g. 22:00-04:00)",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="shiftrule",
            index=models.Index(
                fields=["shift", "active_from", "active_to"],
                name="shiftrule_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavetype",
            constraint=models.CheckConstraint(
                condition=models.Q(("paid_pct__gte", 0), ("paid_pct__lte", 100)),
                name="leavetype_paid_pct_0_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="leavetype",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                models.F("company"),
                name="leavetype_company_code_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftrule",
            constraint=models.UniqueConstraint(
                fields=(
                    "shift",
                    "kind",
                    "value",
                    "active_from",
                    "active_to",
                    "weekdays",
                ),
                name="uniq_rule_signature_per_shift",
            ),
        ),
    ]
