# Generated by Django 5.2.4 on 2025-08-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pagasys", "0016_alter_leavetype_unique_together_company_timezone_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["designation", "employment_type"], name="emp_desig_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rosterentry",
            index=models.Index(fields=["date"], name="roster_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("branch", "name"), name="uniq_department_name_per_branch"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("branch", "name"), name="uniq_project_name_per_branch"
            ),
        ),
    ]
