# Generated by Django 5.2.4 on 2025-08-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pagasys", "0017_employee_emp_desig_type_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["visa_type"], name="employee_visa_type_idx"),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="uniq_branch_name_per_company"
            ),
        ),
    ]
