# Generated by Django 5.2.4 on 2025-08-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0017_shiftrule_refactor"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attevent",
            name="att_event_emp_ts_device_unique",
        ),
        migrations.RenameIndex(
            model_name="attevent",
            new_name="attevent_co_emp_ts_idx",
            old_name="att_event_comp_emp_ts_idx",
        ),
        migrations.AddConstraint(
            model_name="attevent",
            constraint=models.UniqueConstraint(
                fields=("employee", "device", "ts"), name="uniq_event_emp_device_ts"
            ),
        ),
    ]
