# Generated by Django 5.2.4 on 2025-08-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0018_remove_attevent_att_event_emp_ts_device_unique_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="attpair",
            constraint=models.UniqueConstraint(
                fields=("employee", "in_event"), name="uniq_attpair_employee_in_event"
            ),
        ),
    ]
