# Generated by Django 5.2.4 on 2025-08-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pagasys", "0018_employee_employee_visa_type_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["hire_date"], name="emp_hire_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="project_end_on_or_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="tradelicense",
            constraint=models.CheckConstraint(
                condition=models.Q(("expiry_date__gte", models.F("issued_date"))),
                name="license_expiry_after_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="tradelicense",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_visas__gt", 0)),
                name="license_max_visas_positive",
            ),
        ),
    ]
