# Generated by Django 5.2.4 on 2025-08-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0019_attpair_unique_in_event"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attevent",
            name="uniq_event_emp_device_ts",
        ),
        migrations.RenameIndex(
            model_name="attevent",
            new_name="pagasys_att_company_8227c2_idx",
            old_name="attevent_co_emp_ts_idx",
        ),
        migrations.AddField(
            model_name="device",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether the device can ingest events"
            ),
        ),
        migrations.AddConstraint(
            model_name="attevent",
            constraint=models.UniqueConstraint(
                fields=("employee", "ts", "device"), name="uniq_att_event_emp_ts_device"
            ),
        ),
    ]
