# Generated by Django 5.2.4 on 2025-08-22 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0019_employee_emp_hire_date_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department assigned; protected from deletion",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="pagasys.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project assigned; protected from deletion",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="pagasys.project",
            ),
        ),
    ]
