# Generated by Django 5.2.4 on 2025-08-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0020_remove_attevent_uniq_event_emp_device_ts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attevent",
            name="device",
            field=models.ForeignKey(
                blank=True,
                help_text="Device used for the event",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="pagasys.device",
            ),
        ),
    ]
