# Generated by Django 5.2.4 on 2025-08-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0020_remove_attevent_uniq_event_emp_device_ts_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attevent",
            name="uniq_att_event_emp_ts_device",
        ),
        migrations.AddConstraint(
            model_name="attevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("direction", "UNK"), _negated=True),
                fields=("employee", "ts", "device"),
                name="uniq_att_event_emp_ts_device",
            ),
        ),
    ]
