# Generated by Django 5.2.4 on 2025-08-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0020_remove_attevent_uniq_event_emp_device_ts_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leavetype",
            unique_together={("company", "name")},
        ),
        migrations.AddField(
            model_name="leavetype",
            name="code",
            field=models.CharField(
                default="GEN", help_text="Short code for leave type", max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leavetype",
            name="max_days_per_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of days permitted per year",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="requires_doc",
            field=models.BooleanField(
                default=False, help_text="Whether supporting documentation is required"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leavetype",
            unique_together={("company", "code"), ("company", "name")},
        ),
    ]
