# Generated by Django 5.2.4 on 2025-08-18 11:48

from django.db import migrations, models


def normalize_kind(apps, schema_editor):
    ShiftRule = apps.get_model("pagasys", "ShiftRule")
    alias_map = {
        "ramadan reduction": "ramadan_reduce_minutes",
        "Ramadan reduction": "ramadan_reduce_minutes",
        "ramadan_reduction": "ramadan_reduce_minutes",
    }
    for rule in ShiftRule.objects.all():
        new_kind = alias_map.get(rule.kind)
        if new_kind:
            rule.kind = new_kind
            rule.save(update_fields=["kind"])


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0020_remove_attevent_uniq_event_emp_device_ts_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_kind, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="shiftrule",
            name="kind",
            field=models.CharField(
                choices=[("ramadan_reduce_minutes", "Ramadan reduction")],
                help_text="Rule kind",
                max_length=50,
            ),
        ),
    ]
