# Generated by Django 5.2.4 on 2025-08-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0020_alter_employee_department_alter_employee_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="rosterentry",
            name="is_holiday",
            field=models.BooleanField(
                default=False,
                help_text="Marks the day as a holiday. Auto-set if date falls on a holiday",
            ),
        ),
        migrations.AddField(
            model_name="rosterentry",
            name="is_holiday_calendar",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Indicates the date was a holiday when the entry was created",
            ),
        ),
    ]
