# Generated by Django 5.2.4 on 2025-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0020_alter_employee_department_alter_employee_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="rosterentry",
            name="is_holiday",
            field=models.BooleanField(
                default=False,
                help_text="Treat the day as a holiday (auto-set for calendar holidays)",
            ),
        ),
        migrations.AddField(
            model_name="rosterentry",
            name="was_holiday",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="True if the date was a holiday when scheduled",
            ),
        ),
    ]
