# Generated by Django 5.2.4 on 2025-08-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0020_remove_attevent_uniq_event_emp_device_ts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attday",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("leave", "Leave"),
                    ("holiday", "Holiday"),
                    ("rest", "Rest Day"),
                    ("partial", "Partial Day"),
                    ("missing", "Missing Punch"),
                ],
                help_text="Attendance status",
                max_length=20,
            ),
        ),
    ]
