# Generated by Django 5.2.4 on 2025-08-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0021_alter_attevent_device"),
        ("pagasys", "0021_alter_shiftrule_kind"),
        ("pagasys", "0021_remove_attevent_uniq_att_event_emp_ts_device_and_more"),
    ]

    operations = []
