# Generated by Django 5.2.4 on 2025-08-24 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0021_rosterentry_is_holiday_rosterentry_was_holiday"),
    ]

    operations = [
        migrations.CreateModel(
            name="HolidayAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Holiday name at change time", max_length=255
                    ),
                ),
                (
                    "old_date",
                    models.DateField(
                        blank=True, help_text="Previous holiday date", null=True
                    ),
                ),
                (
                    "new_date",
                    models.DateField(
                        blank=True, help_text="New holiday date", null=True
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("updated", "updated"),
                            ("deleted", "deleted"),
                        ],
                        help_text="Change action",
                        max_length=7,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the change occurred"
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        help_text="Calendar this audit entry relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holiday_audit_logs",
                        to="pagasys.workcalendar",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
