# Generated by Django 5.2.4 on 2025-08-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0022_merge_20250818_1315"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="doc",
            field=models.FileField(
                blank=True,
                help_text="Supporting document",
                null=True,
                upload_to="leave_docs/",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="meta",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional metadata"
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="part_day_minutes",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Partial day leave minutes"
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                help_text="Request status",
                max_length=20,
            ),
        ),
    ]
