# Generated by Django 5.2.4 on 2025-08-18 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0022_merge_20250818_1318"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaveday",
            old_name="minutes",
            new_name="minutes_covered",
        ),
        migrations.RenameField(
            model_name="leaveday",
            old_name="pay_percent",
            new_name="paid_pct",
        ),
        migrations.RenameField(
            model_name="leaverequest",
            old_name="pay_percent",
            new_name="paid_pct",
        ),
        migrations.RenameField(
            model_name="leavetype",
            old_name="pay_percent",
            new_name="paid_pct",
        ),
    ]
