# Generated by Django 5.2.4 on 2025-08-30 20:28

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0022_holidayauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="current_address",
            field=models.TextField(blank=True, help_text="Current residential address"),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                help_text="Gender",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="nationality",
            field=django_countries.fields.CountryField(
                blank=True, help_text="Nationality", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="payment_status",
            field=models.CharField(
                choices=[("wps", "WPS"), ("cash", "Cash")],
                default="cash",
                help_text="Payment method: WPS or Cash",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="permanent_address",
            field=models.TextField(
                blank=True, help_text="Permanent home country address"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="primary_contact",
            field=models.CharField(
                blank=True, help_text="Primary contact number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="secondary_contact",
            field=models.CharField(
                blank=True, help_text="Secondary contact number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="unified_id",
            field=models.CharField(blank=True, help_text="Unified ID", max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="visa_file_number",
            field=models.CharField(
                blank=True, help_text="Government visa file number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="wps_account_number",
            field=models.CharField(
                blank=True,
                help_text="WPS account number (required if payment status is WPS)",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="visa_type",
            field=models.CharField(
                choices=[
                    ("company", "Company"),
                    ("personal", "Personal"),
                    ("visit", "Visit"),
                ],
                default="company",
                help_text="Whether the employee uses a company or personal visa",
                max_length=20,
            ),
        ),
    ]
