# Generated by Django 5.2.4 on 2025-08-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0023_leaverequest_doc_leaverequest_meta_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attevent",
            name="uniq_att_event_emp_ts_device",
        ),
        migrations.AddConstraint(
            model_name="attevent",
            constraint=models.UniqueConstraint(
                fields=("employee", "ts", "device"), name="uniq_att_event_emp_ts_device"
            ),
        ),
    ]
