# Generated by Django 5.2.4 on 2025-08-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pagasys", "0023_employee_current_address_employee_gender_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="employee",
            name="employee_license_matches_visa_type",
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(help_text="Date of joining"),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("trade_license__isnull", False), ("visa_type", "company")
                    ),
                    models.Q(
                        ("trade_license__isnull", True),
                        ("visa_type__in", ["personal", "visit"]),
                    ),
                    _connector="OR",
                ),
                name="employee_license_matches_visa_type",
            ),
        ),
    ]
