# Generated by Django 5.2.4 on 2025-08-18

import datetime as dt

from django.db import migrations, models
from django.utils.dateparse import parse_datetime, parse_time


def _parse_dt(value, base_date):
    if not value:
        return None
    result = parse_datetime(value)
    if result is None:
        t = parse_time(value)
        if t is not None:
            result = dt.datetime.combine(base_date, t)
    return result


def forwards(apps, schema_editor):
    RosterEntry = apps.get_model("pagasys", "RosterEntry")
    for entry in RosterEntry.objects.exclude(overrides=None):
        data = entry.overrides or {}
        start = _parse_dt(data.get("start"), entry.date)
        end = _parse_dt(data.get("end"), entry.date)
        if start and end and end <= start:
            end += dt.timedelta(days=1)
        entry.override_start = start
        entry.override_end = end
        if "is_rest_day" in data:
            entry.is_rest_day = bool(data["is_rest_day"])
        entry.save(update_fields=["override_start", "override_end", "is_rest_day"])


def backwards(apps, schema_editor):
    RosterEntry = apps.get_model("pagasys", "RosterEntry")
    for entry in RosterEntry.objects.all():
        data = {}
        if entry.override_start:
            data["start"] = entry.override_start.isoformat()
        if entry.override_end:
            data["end"] = entry.override_end.isoformat()
        if entry.is_rest_day:
            data["is_rest_day"] = entry.is_rest_day
        entry.overrides = data or None
        entry.save(update_fields=["overrides"])


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0022_merge_rosterentry_conflicts"),
    ]

    operations = [
        migrations.AddField(
            model_name="rosterentry",
            name="override_start",
            field=models.DateTimeField(
                blank=True, null=True, help_text="Override shift start"
            ),
        ),
        migrations.AddField(
            model_name="rosterentry",
            name="override_end",
            field=models.DateTimeField(
                blank=True, null=True, help_text="Override shift end"
            ),
        ),
        migrations.AddField(
            model_name="rosterentry",
            name="is_rest_day",
            field=models.BooleanField(
                default=False, help_text="Treat this day as a rest day"
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="rosterentry", name="overrides"
        ),
    ]

