# Generated by Django 5.2.4 on 2025-08-18 13:51

from django.db import migrations, models
from django.utils.dateparse import parse_datetime


def _migrate_overrides(apps, schema_editor):
    RosterEntry = apps.get_model("pagasys", "RosterEntry")
    for roster in RosterEntry.objects.exclude(overrides__isnull=True):
        data = roster.overrides or {}
        start = data.pop("start", data.pop("override_start", None))
        end = data.pop("end", data.pop("override_end", None))
        rest = data.pop("is_rest_day", None)
        if start:
            roster.override_start = parse_datetime(start)
        if end:
            roster.override_end = parse_datetime(end)
        if rest is not None:
            roster.is_rest_day = bool(rest)
        roster.overrides = data or None
        roster.save(update_fields=[
            "override_start",
            "override_end",
            "is_rest_day",
            "overrides",
        ])


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0024_remove_attevent_uniq_att_event_emp_ts_device_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rosterentry",
            name="is_rest_day",
            field=models.BooleanField(
                default=False, help_text="Treat this roster entry as a rest day"
            ),
        ),
        migrations.AddField(
            model_name="rosterentry",
            name="override_end",
            field=models.DateTimeField(
                blank=True, help_text="Override shift end datetime", null=True
            ),
        ),
        migrations.AddField(
            model_name="rosterentry",
            name="override_start",
            field=models.DateTimeField(
                blank=True, help_text="Override shift start datetime", null=True
            ),
        ),
        migrations.RunPython(_migrate_overrides, migrations.RunPython.noop),
    ]
