# Generated by Django 5.2.4 on 2025-08-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0024_remove_employee_employee_license_matches_visa_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.TextField(
                blank=True, help_text="Physical address of the company"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(
                blank=True, help_text="General contact email address", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.URLField(
                blank=True, help_text="URL to the company's logo image"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Primary contact phone number", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, help_text="Official company website"),
        ),
    ]
