# Generated by Django 5.2.4 on 2025-08-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0021_alter_attday_status"),
        ("pagasys", "0025_rosterentry_is_rest_day_rosterentry_override_end_and_more"),
    ]

    operations = []
