# Generated by Django 5.2.4 on 2025-08-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagasys', '0025_company_address_company_email_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address of the branch'),
        ),
        migrations.AddField(
            model_name='employee',
            name='hometown',
            field=models.CharField(blank=True, help_text='Hometown', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='tradelicense',
            name='trade_license_account_number',
            field=models.CharField(blank=True, help_text='Trade license account number', max_length=100),
        ),
    ]
