# Generated by Django 5.2.4 on 2025-09-01 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0026_branch_address_employee_hometown_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="unified_id",
        ),
        migrations.RemoveField(
            model_name="tradelicense",
            name="trade_license_account_number",
        ),
        migrations.AddField(
            model_name="employee",
            name="c3_id",
            field=models.CharField(blank=True, help_text="C3 ID", max_length=50),
        ),
        migrations.AddField(
            model_name="employee",
            name="wps_id",
            field=models.CharField(blank=True, help_text="WPS ID", max_length=50),
        ),
        migrations.AddField(
            model_name="tradelicense",
            name="establishment_card_number",
            field=models.CharField(
                blank=True, help_text="Establishment card number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="tradelicense",
            name="license_document",
            field=models.FileField(
                blank=True,
                help_text="Scanned copy of the trade license",
                null=True,
                upload_to="trade_licenses/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Company logo image",
                null=True,
                upload_to="company_logos/",
            ),
        ),
    ]
