# Generated by Django 5.2.4 on 2025-08-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0027_remove_attevent_uniq_att_event_emp_ts_device_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="is_public",
            field=models.BooleanField(default=True, help_text="Public holiday?"),
        ),
    ]
