# Generated by Django 5.2.4 on 2025-09-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0028_tradelicense_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tradelicense",
            name="license_expiry_after_issue",
        ),
        migrations.AlterField(
            model_name="tradelicense",
            name="branches",
            field=models.ManyToManyField(
                blank=True,
                help_text="Which branches this license covers",
                related_name="licenses",
                to="pagasys.branch",
            ),
        ),
        migrations.AlterField(
            model_name="tradelicense",
            name="expiry_date",
            field=models.DateField(
                blank=True, help_text="Date license expires", null=True
            ),
        ),
        migrations.AlterField(
            model_name="tradelicense",
            name="issued_date",
            field=models.DateField(
                blank=True, help_text="Date license was issued", null=True
            ),
        ),
        migrations.AddConstraint(
            model_name="tradelicense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expiry_date__isnull", True),
                    ("issued_date__isnull", True),
                    ("expiry_date__gte", models.F("issued_date")),
                    _connector="OR",
                ),
                name="license_expiry_after_issue",
            ),
        ),
    ]
