# Generated by Django 5.2.4 on 2025-08-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0028_holiday_is_public"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shifttemplate",
            old_name="rounding",
            new_name="rounding_min",
        ),
        migrations.RemoveField(
            model_name="shifttemplate",
            name="grace_minutes",
        ),
        migrations.AddField(
            model_name="shifttemplate",
            name="early_leave_before_min",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Minutes early leave before counting"
            ),
        ),
        migrations.AddField(
            model_name="shifttemplate",
            name="grace_in_min",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Grace minutes for clock-in"
            ),
        ),
        migrations.AddField(
            model_name="shifttemplate",
            name="grace_out_min",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Grace minutes for clock-out"
            ),
        ),
        migrations.AddField(
            model_name="shifttemplate",
            name="late_after_min",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Minutes late before counting"
            ),
        ),
    ]
