# Generated by Django 5.2.4 on 2025-08-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0029_rename_rounding_shifttemplate_rounding_min_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftrule",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ramadan_reduce_minutes", "Ramadan reduction"),
                    ("weekly_rest_day", "Weekly rest day"),
                    ("night_ot_window", "Night OT window"),
                    ("max_daily_hours", "Max daily hours"),
                ],
                help_text="Rule kind",
                max_length=50,
            ),
        ),
    ]
