# Generated by Django 5.2.4 on 2025-09-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagasys", "0030_company_bank_account_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="special_notes",
            field=models.TextField(
                blank=True, help_text="Special notes about the employee"
            ),
        ),
    ]
