# Generated by Django 5.2.4 on 2025-09-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pagasys", "0031_employee_special_notes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="employee",
            name="emp_name_idx",
        ),
        migrations.AddField(
            model_name="employee",
            name="middle_name",
            field=models.CharField(blank=True, help_text="Middle name", max_length=150),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["first_name", "middle_name", "last_name"], name="emp_name_idx"
            ),
        ),
    ]
