# Generated by Django 5.2.4 on 2025-09-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagasys', '0032_add_employee_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='c3_id',
            field=models.CharField(blank=True, help_text='C3 ID (not allowed for personal or visit visas)', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='payment_status',
            field=models.CharField(choices=[('wps', 'WPS'), ('cash', 'Cash')], default='cash', help_text='Payment method: WPS or Cash. Automatically cash for personal or visit visas', max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='visa_type',
            field=models.CharField(choices=[('company', 'Company'), ('personal', 'Personal'), ('visit', 'Visit')], default='company', help_text='Whether the employee uses a company, personal, or visit visa', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wps_account_number',
            field=models.CharField(blank=True, help_text='WPS account number (required if payment status is WPS; not allowed for personal or visit visas)', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wps_id',
            field=models.CharField(blank=True, help_text='WPS ID (not allowed for personal or visit visas)', max_length=50),
        ),
        migrations.AlterField(
            model_name='tradelicense',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Which branches this license covers. Leave empty for a company-wide license', related_name='licenses', to='pagasys.branch'),
        ),
    ]
