# Generated by Django 5.2.4 on 2025-09-04 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pagasys", "0032_add_employee_middle_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("partial_start", models.TimeField(blank=True, null=True)),
                ("partial_end", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("cancelled", "cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by_id", models.IntegerField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagasys.leavetype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaveDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("paid_pct", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "portion",
                    models.DecimalField(decimal_places=2, default=1, max_digits=4),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pagasys.leavetype",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="attendance.leaverequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("work_min", models.IntegerField(default=0)),
                ("unpaid_break_min", models.IntegerField(default=0)),
                ("paid_break_min", models.IntegerField(default=0)),
                ("late_min", models.IntegerField(default=0)),
                ("early_leave_min", models.IntegerField(default=0)),
                ("ot_regular_min", models.IntegerField(default=0)),
                ("ot_night_min", models.IntegerField(default=0)),
                ("ot_holiday_min", models.IntegerField(default=0)),
                ("is_holiday", models.BooleanField(default=False)),
                ("is_rest_day", models.BooleanField(default=False)),
                ("on_leave", models.BooleanField(default=False)),
                (
                    "leave_portion",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "present"),
                            ("absent", "absent"),
                            ("leave", "leave"),
                            ("holiday", "holiday"),
                            ("rest", "rest"),
                            ("partial", "partial"),
                        ],
                        default="absent",
                        max_length=16,
                    ),
                ),
                ("pairs_count", models.IntegerField(default=0)),
                ("punches_used", models.IntegerField(default=0)),
                ("anomalies", models.JSONField(default=dict)),
                ("compute_version", models.IntegerField(default=1)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("locked", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="att_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pagasys.rosterentry",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pagasys.shifttemplate",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["employee", "date"],
                        name="attendance__employe_c6809d_idx",
                    ),
                    models.Index(
                        fields=["locked"], name="attendance__locked_e08b86_idx"
                    ),
                ],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="AttPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Roster date this pair belongs to"),
                ),
                ("in_event_id", models.IntegerField()),
                ("out_event_id", models.IntegerField(blank=True, null=True)),
                ("in_ts", models.DateTimeField()),
                ("out_ts", models.DateTimeField(blank=True, null=True)),
                ("duration_min", models.IntegerField(default=0)),
                ("cross_midnight", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[("auto", "auto"), ("manual", "manual")],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "anomaly",
                    models.JSONField(
                        default=dict,
                        help_text="e.g. {'missing_out':true, 'duplicate':true}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="att_pairs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["employee", "date"],
                        name="attendance__employe_a5022d_idx",
                    ),
                    models.Index(
                        fields=["employee", "in_ts"],
                        name="attendance__employe_f53249_idx",
                    ),
                ],
                "unique_together": {("employee", "in_event_id")},
            },
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "date_from", "date_to"],
                name="attendance__employe_74e69f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(fields=["status"], name="attendance__status_6e3dfd_idx"),
        ),
        migrations.AddIndex(
            model_name="leaveday",
            index=models.Index(
                fields=["employee", "date"], name="attendance__employe_0bc8e9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaveday",
            unique_together={("employee", "date", "request")},
        ),
    ]
