# Generated by Django 5.2.4 on 2025-09-15 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attadjustment',
            new_name='attendance__employe_9dea9e_idx',
            old_name='attendance_attadjust_employee_date_idx',
        ),
        migrations.AlterField(
            model_name='attadjustment',
            name='created_by_id',
            field=models.IntegerField(help_text='Identifier of the user who created the adjustment. Set automatically from the authenticated user.'),
        ),
        migrations.AlterField(
            model_name='attadjustment',
            name='date',
            field=models.DateField(help_text='Roster date the adjustment applies to'),
        ),
        migrations.AlterField(
            model_name='attadjustment',
            name='delta_ot_holiday_min',
            field=models.IntegerField(default=0, help_text='Additive minutes applied to ot_holiday_min'),
        ),
        migrations.AlterField(
            model_name='attadjustment',
            name='delta_ot_night_min',
            field=models.IntegerField(default=0, help_text='Additive minutes applied to ot_night_min'),
        ),
        migrations.AlterField(
            model_name='attadjustment',
            name='delta_ot_regular_min',
            field=models.IntegerField(default=0, help_text='Additive minutes applied to ot_regular_min'),
        ),
        migrations.AlterField(
            model_name='attadjustment',
            name='delta_paid_break_min',
            field=models.IntegerField(default=0, help_text='Additive minutes applied to paid_break_min'),
        ),
        migrations.AlterField(
            model_name='attadjustment',
            name='delta_unpaid_break_min',
            field=models.IntegerField(default=0, help_text='Additive minutes applied to unpaid_break_min'),
        ),
        migrations.AlterField(
            model_name='attadjustment',
            name='delta_work_min',
            field=models.IntegerField(default=0, help_text='Additive minutes applied to work_min'),
        ),
        migrations.AlterField(
            model_name='attadjustment',
            name='employee',
            field=models.ForeignKey(help_text='Employee whose day is adjusted', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attadjustment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attadjustment',
            name='override_status',
            field=models.CharField(blank=True, help_text="Override computed status (e.g. 'present')", max_length=16),
        ),
        migrations.AlterField(
            model_name='attadjustment',
            name='reason',
            field=models.CharField(help_text='Human-readable reason for the adjustment', max_length=255),
        ),
        migrations.AlterField(
            model_name='attday',
            name='anomalies',
            field=models.JSONField(default=dict, help_text='Counts keyed by canonical anomaly names: unpaired_out, missing_out_closed_at_next_in, missing_out, auto_closed, capped, face_required_no_match, geofence_rule_violation, outside_scope, manual_adjustments_applied'),
        ),
        migrations.AlterField(
            model_name='attday',
            name='compute_version',
            field=models.IntegerField(default=1, help_text='Internal algorithm version used for this compute'),
        ),
        migrations.AlterField(
            model_name='attday',
            name='early_leave_min',
            field=models.IntegerField(default=0, help_text='Minutes left early before shift end after grace'),
        ),
        migrations.AlterField(
            model_name='attday',
            name='late_min',
            field=models.IntegerField(default=0, help_text='Minutes late beyond shift start after grace'),
        ),
        migrations.AlterField(
            model_name='attday',
            name='leave_portion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Portion of the day covered by approved leave (0-1)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='attday',
            name='locked',
            field=models.BooleanField(default=False, help_text='Freeze this day to prevent recomputation or adjustments'),
        ),
        migrations.AlterField(
            model_name='attday',
            name='ot_holiday_min',
            field=models.IntegerField(default=0, help_text='Overtime minutes worked on holidays'),
        ),
        migrations.AlterField(
            model_name='attday',
            name='ot_night_min',
            field=models.IntegerField(default=0, help_text='Overtime minutes classified as night'),
        ),
        migrations.AlterField(
            model_name='attday',
            name='ot_regular_min',
            field=models.IntegerField(default=0, help_text='Overtime minutes outside night/holiday buckets'),
        ),
        migrations.AlterField(
            model_name='attday',
            name='paid_break_min',
            field=models.IntegerField(default=0, help_text='Paid break minutes that do not reduce work_min'),
        ),
        migrations.AlterField(
            model_name='attday',
            name='pairs_count',
            field=models.IntegerField(default=0, help_text='Number of AttPair sessions contributing to this day'),
        ),
        migrations.AlterField(
            model_name='attday',
            name='punches_used',
            field=models.IntegerField(default=0, help_text='Total punch events used to build the pairs'),
        ),
        migrations.AlterField(
            model_name='attday',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('leave', 'leave'), ('holiday', 'holiday'), ('rest', 'rest'), ('partial', 'partial')], default='absent', help_text='Final attendance status consumed by payroll and reports', max_length=16),
        ),
        migrations.AlterField(
            model_name='attday',
            name='unpaid_break_min',
            field=models.IntegerField(default=0, help_text='Total unpaid break minutes deducted from work_min'),
        ),
        migrations.AlterField(
            model_name='attday',
            name='work_min',
            field=models.IntegerField(default=0, help_text='Net work minutes after unpaid breaks and deductions'),
        ),
        migrations.AlterField(
            model_name='attpair',
            name='anomaly',
            field=models.JSONField(default=dict, help_text="Canonical anomalies detected for this pair, e.g. {'missing_out_closed_at_next_in': true}"),
        ),
        migrations.AlterField(
            model_name='attpair',
            name='cross_midnight',
            field=models.BooleanField(default=False, help_text='True if out_ts falls on the day after in_ts'),
        ),
        migrations.AlterField(
            model_name='attpair',
            name='duration_min',
            field=models.IntegerField(default=0, help_text='Minutes between in_ts and out_ts, capped per policy'),
        ),
        migrations.AlterField(
            model_name='attpair',
            name='in_event_id',
            field=models.IntegerField(help_text='ID of the originating IN punch event'),
        ),
        migrations.AlterField(
            model_name='attpair',
            name='in_ts',
            field=models.DateTimeField(help_text='Timestamp of the IN punch'),
        ),
        migrations.AlterField(
            model_name='attpair',
            name='out_event_id',
            field=models.IntegerField(blank=True, help_text='ID of the OUT punch event, if any', null=True),
        ),
        migrations.AlterField(
            model_name='attpair',
            name='out_ts',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the OUT punch, if any', null=True),
        ),
        migrations.AlterField(
            model_name='attpair',
            name='source',
            field=models.CharField(choices=[('auto', 'auto'), ('manual', 'manual')], default='auto', help_text="Origin of the pair; 'auto' punches open a new session or close the current one, while 'manual' pairs are entered by managers", max_length=10),
        ),
        migrations.AlterField(
            model_name='leaveday',
            name='paid_pct',
            field=models.DecimalField(decimal_places=2, help_text='Percent of this leave day that is paid (0-100)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='leaveday',
            name='portion',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Portion of the day covered by leave (1=full, 0.5=half)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='partial_end',
            field=models.TimeField(blank=True, help_text='Time when leave ends for a partial day', null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='partial_start',
            field=models.TimeField(blank=True, help_text='Time when leave begins for a partial day', null=True),
        ),
    ]
